name: BUILD

on:
  push:
    branches:
      - main  # or the branch you want to monitor
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify the Node.js version you want to use

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint

    - name: Build the project
      run: npm run build
